language:
  - go
  - node_js

cache:
  directories:
  - node_modules

go:
- "1.11.x"
node_js:
- "6"
- "7"
- "8"

before_install:
- cd frontend
- npm install npm@6 -g
- npm i -g npm
- npm cache verify
- npm prune
- npm update

install:
- npm install

script:
- npm run ci:travis
- cd ..
- go build main.go
